//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "User name is required.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Age is required.")]
        [Range(18, 120,ErrorMessage = "Please enter a number between 18 and 120.")]
        public int Age { get; set; }
        public string Gender { get; set; }
        [Required(ErrorMessage = "Email is required.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Phone is required.")]
        [RegularExpression("[0-9]+", ErrorMessage = "This phone number is not valid.")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Address is required.")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Height is required.")]
        [Range(0, 300, ErrorMessage = "Please enter a number between 0 and 300.")]
        public decimal Height { get; set; }
        [Required(ErrorMessage = "Weight is required.")]
        [Range(0, 200, ErrorMessage = "Please enter a number between 0 and 200.")]
        public decimal Weight { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
