//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Order
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Costomer is required.")]
        public int Userid { get; set; }
        [Required(ErrorMessage = "Item name is required.")]
        public string Item { get; set; }
        [Required(ErrorMessage = "Start time is required.")]
        public System.DateTime Start { get; set; }
        [Required(ErrorMessage = "Duration is required.")]
        [Range(0, 10, ErrorMessage = "Please enter a number between 0 and 10.")]
        public int Duration { get; set; }
        [Required(ErrorMessage = "Price is required.")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter a number.")]
        public decimal Price { get; set; }
        [Required(ErrorMessage = "Content is required.")]
        public string Content { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
